# Generated by Django 3.0.3 on 2021-08-02 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adoptions', '0002_pet_vaccinations'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pet',
            old_name='submittter',
            new_name='submitter',
        ),
    ]
